import MediaStreamManagerModule, {
  EVT_INCOMING_MEDIA_STREAM_TRACK_ADD,
  EVT_INCOMING_MEDIA_STREAM_TRACK_REMOVE,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_ADD,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_REMOVE,
} from "./ZenRTCPeer.MediaStreamManagerModule";

export default MediaStreamManagerModule;
export {
  EVT_INCOMING_MEDIA_STREAM_TRACK_ADD,
  EVT_INCOMING_MEDIA_STREAM_TRACK_REMOVE,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_ADD,
  EVT_OUTGOING_MEDIA_STREAM_TRACK_REMOVE,
};
