import VirtualServerZenRTCPeerManager, {
  EVT_UPDATED,
  EVT_DESTROYED,
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DESTROYED,
  EVT_PEER_UPDATED,
} from "./VirtualServerZenRTCPeerManager";

export default VirtualServerZenRTCPeerManager;
export {
  EVT_UPDATED,
  EVT_DESTROYED,
  EVT_PEER_CONNECTED,
  EVT_PEER_DISCONNECTED,
  EVT_PEER_DESTROYED,
  EVT_PEER_UPDATED,
};
