export const RANDOM_LEADING_EDGE = [
  "WHAT ARE YOU DOING WITH YOUR LIFE?",
  "SO, TELL ME ABOUT YOUR PROBLEMS",
  "WHAT DO YOU WANT TO TALK ABOUT?",
  "WHAT MAKES YOU, YOU?",
  "WHY ARE YOU HERE?",
  "DO YOU KNOW WHY YOU'RE HERE?",
  "HOW IS YOUR MEMORY?",
  "DO YOU REMEMBER OUR LAST CONVERSATION?",
  "RED PILL OR BLUE PILL?",
];

export const NEED_MORE_INFORMATION = [
  "I NEED MORE INFORMATION",
  "TELL ME MORE",
  "EXPLAIN IN MORE DETAIL",
  "GO ON...",
];
