###
# IMPORTANT: This Docker Compose configuration should only be used in
# development environments and is not suitable for production use.
###

version: "3"

networks:
  reshell-development-network:

services:
  dev-ssl:
    build: ./dev-ssl
    # environment:
    #   PROXY_ADDRESS: http://reshell-host.bridge-prototype:3002
    networks:
      - reshell-development-network
    ports:
      - 8443:443
    logging:
      driver: none # Disable spammy logs

  reshell:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      NODE_ENV: development
      PORT: 3001
      HOST_BRIDGE_PORT: 3002
      FRONTEND_PROXY_URL: http://reshell:3001
    networks:
      - reshell-development-network
    volumes:
      - ./:/app
