# NOTE: This Dockerfile, or portions within, will probably wind up becoming part of HostBridge

# TODO: Look into https://devopscube.com/run-docker-in-docker

FROM ubuntu:20.04

# @see https://grigorkh.medium.com/fix-tzdata-hangs-docker-image-build-cdb52cc3360d
ENV TZ=America/Managua
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update \
  && apt-get install -y \
  npm \
  openssh-client \
  && apt-get clean

# Mount third-party storage backends (i.e. AWS, Google Drive, Dropbox)
# @see https://rclone.org/install/

# @see https://docs.npmjs.com/cli/v7/using-npm/config/
# RUN npm install -g --unsafe-perm node-pty

WORKDIR /app

# This sets the root password!
# TODO: Make this configurable and do not leave in Dockerfile
# RUN echo "root:Docker!" | chpasswd

# TODO: Implement ability to obtain dynamic username
RUN useradd -ms /bin/bash user

USER user

COPY . ./

CMD ["npm", "run", "start:frontend-with-hostbridge-proxy"]