import React from "react";
import Center from "@components/Center";
import Avatar from "@components/Avatar";
import Padding from "@components/Padding";
import Form from "@components/Form";

import RandomIcon from "@icons/RandomIcon";

// TODO: Add PropTypes
export default function LocalUserProfileForm({
  name = "",
  onGenerateName,
  description = "",
  onGenerateDescription,
  avatarURL = "",
  onGenerateAvatar,
  onChange,
  onSubmit,
  onCancel,
  isDirty,
}) {
  return (
    <Center canOverflow={true}>
      <Padding>
        <Form
          style={{ display: "inline-block", width: "100%", maxWidth: 500 }}
          onChange={onChange}
          onSubmit={onSubmit}
        >
          {
            // TODO: Add error / isValid handling
          }
          {({ errors, isValid, submit, validate }) => {
            return (
              <React.Fragment>
                <div className="note" style={{ marginBottom: 10 }}>
                  User profiles are automatically generated by default. Changes
                  here are saved to local storage.
                </div>
                <div style={{ marginBottom: 20 }}>
                  <div
                    style={{
                      width: 200,
                      height: 200,
                      display: "inline-block",
                      border: "8px rgba(255,255,255,.4) solid",
                      borderRadius: 200,
                      overflow: "hidden",
                      backgroundColor: "rgba(255,255,255,.1)",
                      color: "#000",
                      fontSize: ".8rem",
                    }}
                  >
                    <input type="hidden" name="avatarURL" value={avatarURL} />
                    <Center>
                      {avatarURL && (
                        // TODO: Use AudioBorderAvatar instead
                        <Avatar src={avatarURL} name={name} size="100%" />
                      )}
                    </Center>
                  </div>

                  <div>
                    <button type="button" onClick={onGenerateAvatar}>
                      Randomize <RandomIcon style={{ fontSize: "1.2rem" }} />
                    </button>
                  </div>
                </div>

                <table style={{ width: "100%" }} className="layout">
                  <tbody>
                    <tr>
                      <td style={{ textAlign: "left" }}>
                        <label>Name</label>
                      </td>
                      <td>
                        <input
                          type="text"
                          name="name"
                          style={{ width: "100%" }}
                          value={name}
                          onChange={validate}
                        />
                      </td>
                      <td>
                        <button type="button" onClick={onGenerateName}>
                          <RandomIcon
                            style={{ fontSize: "1.2rem" }}
                            title="Random name"
                          />
                        </button>
                      </td>
                    </tr>
                    <tr>
                      <td colSpan="2">
                        <div style={{ textAlign: "left" }}>
                          <label>Description</label>
                          <textarea
                            name="description"
                            placeholder=""
                            style={{ width: "100%", height: 150 }}
                            value={description}
                            onChange={validate}
                          ></textarea>
                        </div>
                      </td>
                      <td style={{ verticalAlign: "bottom" }}>
                        <button type="button" onClick={onGenerateDescription}>
                          <RandomIcon
                            style={{ fontSize: "1.2rem" }}
                            title="Random description"
                          />
                        </button>
                      </td>
                    </tr>
                  </tbody>
                </table>

                {/*
                <div>
                  <h2>Permissions</h2>
                  <div style={{ display: "inline-block" }}>
                    <label>Allow others to search for you</label>
                    <br />
                    <button disabled>Yes</button>
                    <button>No</button>
                  </div>
                </div>
                */}
                {
                  // TODO: Move cancel / save buttons to bottom of view (layout footer)
                }

                <div
                  style={{
                    marginTop: 20,
                    textAlign: "right",
                    overflow: "nowrap",
                    paddingRight: 20,
                  }}
                >
                  <span
                    className="note"
                    style={{ color: isDirty ? "yellow" : null }}
                  >
                    Profile is {isDirty ? "not saved" : "saved"}
                  </span>

                  <div style={{ overflow: "nowrap", display: "inline-block" }}>
                    <button
                      type="button"
                      onClick={onCancel}
                      style={{
                        marginLeft: 10,
                        paddingRight: 20,
                        paddingLeft: 20,
                      }}
                      disabled={!isDirty}
                    >
                      Cancel
                    </button>
                    <button
                      type="button"
                      onClick={submit}
                      style={{
                        backgroundColor: "#347FE8",
                        marginLeft: 10,
                        paddingRight: 20,
                        paddingLeft: 20,
                      }}
                      disabled={!isDirty}
                    >
                      Save
                    </button>
                  </div>
                </div>
              </React.Fragment>
            );
          }}
        </Form>
      </Padding>
    </Center>
  );
}
